name: Deploy ML App to AKS

on:
  push:
    branches:
      - main  # Triggers deployment when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Up kubectl
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Deploy ML App to AKS
        run: |
          kubectl apply -f ml-deployment.yaml
          kubectl rollout status deployment/ml-app-deployment
          kubectl get services -o wide
